### ISSUE TITLE
[BUG]: Audio transcoding not working with FFMPEG 7

### ISSUE THREAD

**Issue by dkadioglu** [tvheadend/tvheadend#1764]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3.r2368~g554004da

### Platform

Other..

### Architecture

ARMv8 (aarch64)

### Category

Transcoding

### Description

As described in https://github.com/tvheadend/tvheadend/pull/1721 building TVHeadend with FFMPEG 7, I have no more audio except with the profile pass. I hope it is ok to open a new issue for that.
Whenever transcoding is involved, I see this in the log:

```
Aug 25 23:17:58 dkrpitv tvheadend[15102]: transcode: 0001: 01:H264: ==> Copy
Aug 25 23:17:58 dkrpitv tvheadend[15102]: transcode: 0001: 02:MPEG2AUDIO:
==> Using profile webtv-aac
Aug 25 23:17:58 dkrpitv tvheadend[15102]: transcode: 0001: 03:MPEG2AUDIO:
==> Filtered out
Aug 25 23:17:58 dkrpitv tvheadend[15102]: transcode: 0001: 05:DVBSUB: ==>
Filtered out
Aug 25 23:17:58 dkrpitv tvheadend[15102]: transcode: 0001: 06:AC3: ==> Filtered out
Aug 25 23:17:58 dkrpitv tvheadend[15102]: transcode: 0001: 08:MPEG2AUDIO:
==> Filtered out
Aug 25 23:17:58 dkrpitv tvheadend[15102]: transcode: 0001: 09:TEXTSUB: ==> Filtered out
Aug 25 23:17:58 dkrpitv tvheadend[15102]: transcode: 0001: 02:AAC-LATM: [mp2 => aac]: filters: failed to set option: 'ch_layouts'
```

System is an RPi 4 with Arch Linux and self built TVHeadend using the PKGBUILD from AUR: https://aur.archlinux.org/packages/tvheadend-git (I modified the PKGBUILD to force build with FFMPEG 7)

If you need further info, please ask.

**Comment by uknunknown** [comment]
please check if branch: https://github.com/uknunknown/tvheadend/tree/dev_ffmpg7
is fixing your problem.

**Comment by dkadioglu** [comment]
> please check if branch: https://github.com/uknunknown/tvheadend/tree/dev_ffmpg7 is fixing your problem.

Unfortunately not. With that tvheadend crashes:
```
Okt 07 02:31:07 dkrpitv systemd[1]: tvheadend.service: Scheduled restart job, restart counter is at 2.
Okt 07 02:31:07 dkrpitv systemd[1]: tvheadend.service: Consumed 6.544s CPU time.
Okt 07 02:31:07 dkrpitv systemd[1]: tvheadend.service: Failed with result 'core-dump'.
Okt 07 02:31:07 dkrpitv systemd[1]: tvheadend.service: Main process exited, code=dumped, status=11/SEGV
Okt 07 02:31:00 dkrpitv tvheadend[661]: transcode: 0001: 08:DVBSUB: ==> Filtered out
Okt 07 02:31:00 dkrpitv tvheadend[661]: transcode: 0001: 07:AC3: ==> Filtered out
Okt 07 02:31:00 dkrpitv tvheadend[661]: transcode: 0001: 05:MPEG2AUDIO: ==> Filtered out
Okt 07 02:31:00 dkrpitv tvheadend[661]: transcode: 0001: 04:MPEG2AUDIO: ==> Filtered out
Okt 07 02:31:00 dkrpitv tvheadend[661]: transcode: 0001: 03:MPEG2AUDIO: ==> Using profile webtv-aac
Okt 07 02:31:00 dkrpitv tvheadend[661]: transcode: 0001: 02:H264: ==> Copy
Okt 07 02:31:00 dkrpitv tvheadend[661]: subscription: 0001: "HTTP" subscribing on channel "rbb Brandenburg HD", weight: 100, adapter: "Sundtek DVB->Okt 07 02:30:59 dkrpitv tvheadend[661]: mpegts: 10891.25H in Astra_19.2_E - tuning on Sundtek DVB-S/S2 (VIII) #0 : DVB-S #0
```

**Comment by dkadioglu** [comment]
And here is the stack trace, if that helps:
```
 Stack trace of thread 960:
                #0  0x0000ffff8a63fe8c memcpy (libc.so.6 + 0x9fe8c)
                #1  0x0000ffff8bb57760 n/a (libavcodec.so.61 + 0x117760)
                #2  0x0000ffff8bd76bcc n/a (libavcodec.so.61 + 0x336bcc)
                #3  0x0000ffff8bd76f70 n/a (libavcodec.so.61 + 0x336f70)
                #4  0x0000ffff8bd772a4 avcodec_send_frame (libavcodec.so.61 + 0x3372a4)
                #5  0x0000aaaae47831d8 tvh_context_encode_frame (tvheadend + 0x2a31d8)
                #6  0x0000aaaae478370c tvh_context_encode (tvheadend + 0x2a370c)
                #7  0x0000aaaae4784320 tvh_context_decode (tvheadend + 0x2a4320)
                #8  0x0000aaaae4785b44 tvh_stream_handle (tvheadend + 0x2a5b44)
                #9  0x0000aaaae4786118 tvh_transcoder_handle (tvheadend +
0x2a6118)
                #10 0x0000aaaae46e4e28 normalize_ts (tvheadend + 0x204e28)                #11 0x0000aaaae46e589c tsfix_backlog (tvheadend + 0x20589c)
                #12 0x0000aaaae46bdf20 profile_sharer_thread (tvheadend +
0x1ddf20)
                #13 0x0000aaaae4659e30 thread_wrapper (tvheadend + 0x179e30)
                #14 0x0000ffff8a62a624 n/a (libc.so.6 + 0x8a624)
                #15 0x0000ffff8a69064c n/a (libc.so.6 + 0xf064c)
                Stack trace of thread 675:
                #0  0x0000ffff8a690964 epoll_pwait (libc.so.6 + 0xf0964)
                #1  0x0000aaaae469fda0 tvhpoll_wait (tvheadend + 0x1bfda0)                #2  0x0000aaaae476fac4 iptv_input_thread (tvheadend + 0x28fac4)
                #3  0x0000aaaae4659e30 thread_wrapper (tvheadend + 0x179e30)
                #4  0x0000ffff8a62a624 n/a (libc.so.6 + 0x8a624)
                #5  0x0000ffff8a69064c n/a (libc.so.6 + 0xf064c)
                Stack trace of thread 664:
                #0  0x0000ffff8a660680 clock_nanosleep (libc.so.6 + 0xc0680)
                #1  0x0000aaaae4658b90 tvh_usleep (tvheadend + 0x178b90)
                #2  0x0000aaaae4659260 tvh_usleep (tvheadend + 0x179260)
                #3  0x0000aaaae466b254 notify_thread (tvheadend + 0x18b254)
                #4  0x0000aaaae4659e30 thread_wrapper (tvheadend + 0x179e30)
                #5  0x0000ffff8a62a624 n/a (libc.so.6 + 0x8a624)
                #6  0x0000ffff8a69064c n/a (libc.so.6 + 0xf064c)
                Stack trace of thread 668:
                #0  0x0000ffff8a692de4 recv (libc.so.6 + 0xf2de4)
                #1  0x0000ffff8dd5772c n/a (libmediaclient.so + 0x772c)
                #2  0x0000ffff8dd5772c n/a (libmediaclient.so + 0x772c)
                #3  0x0000ffff8dd541c0 __ioctl_time64 (libmediaclient.so + 0x41c0)
                #4  0x0000aaaae475c5d8 linuxdvb_frontend_monitor (tvheadend + 0x27c5d8)
                #5  0x0000ffff80781400 n/a (n/a + 0x0)
                #6  0x0000ffff80781400 n/a (n/a + 0x0)
                ELF object binary architecture: AARCH64
```

**Comment by uknunknown** [comment]
I realized that I forgot to copy changes from Makefile.ffmpeg ... soyou compiled with ffmpeg 6.1.1.
I fixed this problem and also fixed the failure with ffmpeg 6.1.1
Make sure you clean up ('make distclean').
Please try again the same branch.

**Comment by dkadioglu** [comment]
Unfortunately still crashes.
However, from my understanding, I am building with ffmpeg 7.0.2. This is the build info of tvheadend:
```
Configure arguments:
  --datadir=/var/lib --disable-ffmpeg_static --disable-hdhomerun_static --disable-libfdkaac_static --disable-libogg_static --disable-libopus_static --disable-libtheora_static --disable-libvorbis_static --disable-libvpx_static --disable-libx264_static --disable-libx265_static --enable-libav --enable-avahi --enable-pngquant --enable-vaapi --enable-zlib --mandir=/usr/share/man/man1 --prefix=/usr --python=python3

Compiler:
  Using C compiler:                        cc
  Using LD flags:                           -ldvbcsa
  Build for arch:                          aarch64

Binaries:
  Using PYTHON:                            python3
  Using GZIP:                              gzip
  Using BZIP2:                             bzip2

Options:
  pie                                      yes
  ccdebug                                  no
  cardclient                               yes
  cwc                                      yes
  cccam                                    yes
  capmt                                    yes
  constcw                                  yes
  linuxdvb                                 yes
  satip_server                             yes
  satip_client                             yes
  hdhomerun_client                         no
  hdhomerun_server                         yes
  hdhomerun_static                         no
  iptv                                     yes
  tsfile                                   yes
  dvbscan                                  yes
  timeshift                                yes
  trace                                    yes
  avahi                                    yes
  zlib                                     yes
  libav                                    yes
  ffmpeg_static                            no
  libx264                                  yes
  libx264_static                           no
  libx265                                  yes
  libx265_static                           no
  libvpx                                   yes
  libvpx_static                            no
  libtheora                                yes
  libtheora_static                         no
  libvorbis                                yes
  libvorbis_static                         no
  libfdkaac                                no
  libfdkaac_static                         no
  libopus                                  yes
  libopus_static                           no
  nvenc                                    no
  vaapi                                    yes
  mmal                                     no
  omx                                      no
  inotify                                  yes
  epoll                                    yes
  pcre                                     no
  pcre2                                    yes
  uriparser                                yes
  ccache                                   no
  tvhcsa                                   yes
  bundle                                   no
  pngquant                                 yes
  kqueue                                   no
  dbus_1                                   yes
  android                                  no
  gtimer_check                             no
  slow_memoryinfo                          no
  libsystemd_daemon                        no
  pcloud_cache                             yes
  ddci                                     yes
  cclang_threadsan                         yes
  gperftools                               no
  execinfo                                 yes
  W_unused_result                          yes
  f_stack_protector                        yes
  f_stack_protector_strong                 yes
  f_stack_check                            yes
  f_PIE                                    yes
  strlcat                                  yes
  strlcpy                                  yes
  fdatasync                                yes
  getloadavg                               yes
  atomic32                                 yes
  atomic64                                 yes
  atomic_time_t                            yes
  atomic_ptr                               yes
  bitops64                                 yes
  lockowner                                yes
  time_ld                                  yes
  gmtoff                                   yes
  recvmmsg                                 yes
  sendmmsg                                 yes
  ifnames                                  yes
  py_gzip                                  yes
  bin_pkg_config                           yes
  bin_xgettext                             yes
  bin_msgmerge                             yes
  bin_gzip                                 yes
  bin_bzip2                                yes
  ssl                                      yes
  linuxdvbapi                              yes
  linuxdvb_ca                              yes
  upnp                                     yes
  hwaccels                                 yes
  inotify_h                                yes
  inotify_init1                            yes
  dvbcsa                                   yes
  epoll_create1                            yes
  mpegts                                   yes
  mpegts_dvb                               yes

Packages:
  openssl                                  3.3.2
  zlib                                     1.3.1
  libpcre2-8                               10.44
  liburiparser                             0.9.8
  avahi-client                             0.8
  libavfilter                              10.1.100
  libswresample                            5.1.100
  libswscale                               8.1.100
  libavformat                              61.1.100
  libavcodec                               61.3.100
  libavutil                                59.8.100
  libva                                    1.22.0
  libva-drm                                1.22.0
  dbus-1                                   1.14.10

Installation paths:
  Prefix:                                  /usr
  Binaries:                                ${prefix}/bin
  Libraries:                               ${prefix}/lib
  Data files:                              /var/lib
  Man pages:                               /usr/share/man/man1
```
And this is the output of ffmpeg -version:
```
ffmpeg version n7.0.2 Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 14.1.1 (GCC) 20240507
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-fontconfig --enable-frei0r --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d
--enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-opencl --enable-opengl --enable-shared --enable-vapoursynth --enable-version3 --enable-vulkan
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
Or am I doing something wrong here?

**Comment by fossdd** [comment]
At Alpine we've been building tvheadend with ffmpeg 4. But yeah, proper support for ffmpeg 7 would be nice.

**Comment by uknunknown** [comment]
I am not a specialist in RPI ... but some config are standing out:
1. --disable-ffmpeg_static  --> when I want to transcode I use ffmpeg static (it might work even without).
2. vaapi     yes --> I don't think Arch Linux in RPI4 has vaapi support.
3. mmal   no ; omx    no --> I think those are the only HW transcoding capability of RPI4 ... you might one to experiment by enabling those.
You should double check the info above with other sources.

> At Alpine we've been building tvheadend with ffmpeg 4. But yeah, proper support for ffmpeg 7 would be nice

BTW: Can you confirm the master (that use 6.1.1) is working (to confirm config used to build works as of Today)? TVH has transitioned from ffmpeg4 about 2 years a go. Can you confirm if anything in between works on your system?

**Comment by fossdd** [comment]
> BTW: Can you confirm the master (that use 6.1.1) is working (to confirm config used to build works as of Today)? TVH has transitioned from ffmpeg4 about 2 years a go. Can you confirm if anything in between works on your system?

Oh cool, didn't notice master already upgraded. Tested master with the Alpine build system and until now now issues found. Thanks for your work!

**Comment by dkadioglu** [comment]
Sorry, this got lost somehow. And I switched to a RPi 5 now. However, still no sound with ffmpeg 7.1.
> 1. --disable-ffmpeg_static  --> when I want to transcode I use ffmpeg static (it might work even without).

With ffmpeg 6 this worked always fine. With current master I still see this: `transcode: 0004: 02:AAC-LATM: [mp2 => aac]: filters: failed to set option: 'channel_layouts'`
And I have no sound in the webplayer, even with different browsers. 

> * vaapi     yes --> I don't think Arch Linux in RPI4 has vaapi support.
> * mmal   no ; omx    no --> I think those are the only HW transcoding capability of RPI4 ... you might one to experiment by enabling those.
>   You should double check the info above with other sources.

Do you think that just enabling vaapi as build option would lead to no sound or even any errors? At least this is enabled since years in the PKGBUILD and never lead to problems with ffmpeg 6.
mmal and omx are not relevant on a RPi 5.

As mentioned, I am still using the PKGBUILD from here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tvheadend-git

Could the above mentioned error about "channel_layouts" be the culprit here? Or something else?

**Comment by uknunknown** [comment]
I didn't realized that your goal is to build with ffmpeg7 ... If you want to compile to ffmpeg7 you have to pull in https://github.com/tvheadend/tvheadend/pull/1772 .

**Comment by dkadioglu** [comment]
@uknunknown Thank you very much for looking through it again. With the mentioned patch, the error is gone and I have sound again. I have to admit, that due to various patches regarding ffmpeg 7 in the last couple of months, I have probably lost track about which patch is necessary. Apologies.

**Comment by uknunknown** [comment]
You don't have to apologizes; I like to think that we are a strong community ... we are here to help you. Flole is working on the infrastructure issue; hopefully soon we will restart the submission process (to master). Please be patient.
